meme_dict = {
    "CRINGE": "Garip ya da utandırıcı bir şey",
    "LOL": "Komik bir şeye verilen cevap",
    "LMAO": "Çok komik bir şeye verilen cevap",
    "ROFL": "Aşırı komik bir şeye verilen tepki",
    "OMG": "Şaşkınlık veya hayret ifadesi",
    "WTF": "Şaşkınlık, kızgınlık veya anlam verememe ifadesi",
    "BRUH": "Şaşkınlık veya hayal kırıklığı ifadesi",
    "SUS": "Şüpheli veya güvenilmez bir şey",
    "NOOB": "Bir konuda acemi olan kişi",
    "PRO": "Bir konuda çok iyi olan kişi",
    "GOAT": "Bir alanda en iyilerden biri",
    "BASED": "Bir fikri desteklediğini belirten ifade",
    "CAP": "Yalan veya abartı anlamında kullanılır",
    "NO CAP": "Şaka yapmadığını veya doğru söylediğini belirtir",
    "FLEX": "Sahip olunan bir şeyi göstererek övünmek",
    "ROAST": "Biriyle dalga geçmek veya onu tiye almak",
    "MEME": "İnternette yayılan komik içerik",
    "TROLL": "İnsanları kızdırmak veya tepki vermelerini sağlamak",
    "VIBE": "Bir ortamın veya kişinin verdiği his",
    "MOOD": "Bir durumun kişinin ruh halini yansıtması",
    "BASED AF": "Bir fikri çok güçlü şekilde desteklemek",
    "YEET": "Bir şeyi hızlıca veya güçlü biçimde fırlatmak",
    "YIKES": "Rahatsızlık veya şaşkınlık ifadesi",
    "OOF": "Acı, başarısızlık veya hayal kırıklığı tepkisi",
    "F": "Birinin yaşadığı kötü duruma üzüntü belirtmek",
    "W": "Başarı veya galibiyet anlamında kullanılır",
    "L": "Kaybetme veya başarısızlık anlamında kullanılır",
    "WTF BRO": "Anlamsız veya şaşırtıcı bir duruma tepki",
    "SAVAGE": "Cesur veya acımasız bir cevap ya da davranış",
    "SLAY": "Bir şeyi çok iyi yapmak",
    "DRIP": "Havalı kıyafet veya tarz",
    "RIZZ": "Romantik çekicilik veya flört yeteneği",
    "NPC": "Robot gibi veya tepkisiz davranan kişi",
    "MAIN CHARACTER": "Kendini hikâyenin başrolündeymiş gibi gören kişi",
    "DELULU": "Gerçeklikten kopuk veya aşırı hayalperest olmak",
    "SKIBIDI": "Anlamsız, absürt internet mizahında kullanılan ifade",
    "SIGMA": "Bağımsız ve kendi yolunda ilerleyen kişi imajı",
    "GYATT": "Genellikle şaşkınlık veya fiziksel görünüşe tepki",
    "EMOTIONAL DAMAGE": "Bir sözün veya olayın kişiyi kötü etkilemesi",
    "TOUCH GRASS": "İnternetten biraz uzaklaşmayı söyleyen ifade",
    "LAG": "Oyunda veya internette gecikme yaşanması",
    "RAGE QUIT": "Sinirlenip oyunu veya etkinliği bırakmak",
    "GG": "İyi oyun anlamında kullanılır",
    "EZ": "Bir şeyin çok kolay olduğunu belirtir",
    "AFK": "Bilgisayar veya oyundan geçici olarak uzak olmak",
    "IRL": "Gerçek hayatta anlamında kullanılır",
    "POV": "Bir olayın belirli bir bakış açısından anlatılması",
    "FOMO": "Bir şeyi kaçırma korkusu",
    "YOLO": "Hayatın bir kez yaşandığını belirten ifade",
    "BTW": "Bu arada anlamında kullanılır",
    "IDK": "Bilmiyorum anlamında kullanılır",
    "WYD": "Ne yapıyorsun anlamında kullanılır",
}
